version: 2.1

orbs:
  azure-cli: circleci/azure-cli@dev:alpha
  circle-compare-url: iynere/compare-url@0.4.5
  orb-tools: circleci/orb-tools@3.0.0

executors:
  cli:
    resource_class: small
    docker:
      - image: circleci/circleci-cli

  github:
    resource_class: small
    docker:
      - image: cibuilds/github

  lint:
    resource_class: small
    docker:
      - image: singapore/lint-condo

  golang:
    resource_class: small
    docker:
      - image: circleci/golang

  python:
    resource_class: small
    docker:
      - image: circleci/python:2.7-stretch

commands:
  azure-cli-tests:
    description: "Verifies azure-cli install"
    steps:
      - azure-cli/install

      - run:
          name: Verify Azure install
          command: az -v

      - azure-cli/login-with-user

      - run:
          name: Verify login with user
          command: az resource list

      - run: az logout

      - azure-cli/login-with-service-principal

      - run:
          name: Verify login with Service Principal
          command: az resource list

      - run: az logout

      - azure-cli/login-with-user:
          alternate-tenant: true

      - run:
          name: Verify login with user and alternate tenant
          command: az resource list

jobs:
  lint:
    executor: lint
    steps:
      - checkout
      - run: yamllint .

  # validate goes here: see workflow

  publish-dev:
    executor: cli
    steps:
      - checkout

      - attach_workspace:
          at: workspace

      - run:
          name: publish dev versions
          command: |
            # dev:alpha, for integration testing
            circleci orb publish workspace/orb.yml circleci/azure-cli@dev:alpha --token $CIRCLE_TOKEN

            # branch + sha, for transparency
            circleci orb publish workspace/orb.yml circleci/azure-cli@dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN

            # sha only, for potential prod promotion
            circleci orb publish workspace/orb.yml circleci/azure-cli@dev:${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN

      - store_artifacts:
          path: workspace/orb.yml

  trigger-integration:
    executor: github
    parameters:
      tag:
        type: enum
        default: "integration"
        enum: ["integration", master]
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "23:d1:63:44:ad:e7:1a:b0:45:5e:1e:e4:49:ea:63:4e"

      - run:
          name: git config
          command: |
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"
            git config --global user.name "$CIRCLE_USERNAME"

      - circle-compare-url/reconstruct

      - run:
          name: trigger integration workflow, possible patch / minor / major release
          command: |
            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)

            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')

            echo "Commit range: $COMMIT_RANGE"

            if [[ $(git diff $COMMIT_RANGE --name-status | grep -e "src/commands" -e "src/jobs") ]]; then
              INTEGRATION_TAG=<<parameters.tag>>-major-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
            elif [[ $(git diff $COMMIT_RANGE --name-status | grep -e "src/executors" -e "src/examples" -e "src/@orb.yml") ]]; then
              INTEGRATION_TAG=<<parameters.tag>>-minor-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
            else
              INTEGRATION_TAG=<<parameters.tag>>-patch-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
            fi

            git tag $INTEGRATION_TAG
            git push origin $INTEGRATION_TAG

  test-orb-python:
    executor: python
    steps:
      - azure-cli-tests

  test-orb-golang:
    executor: golang
    steps:
      - azure-cli-tests

  test-orb-azure-docker:
    executor: azure-cli/azure-docker
    steps:
      - run: az -v
      - azure-cli-tests

  dev-promote-prod:
    executor: cli
    parameters:
      release:
        type: enum
        default: "patch"
        enum: ["patch", "minor", "major"]
    steps:
      - run:
          name: major release if changes to src/commands or src/jobs; minor if to src/examples, src/executors, or src/@orb.yml; otherwise patch
          command: circleci orb publish promote circleci/azure-cli@dev:${CIRCLE_SHA1:0:7} <<parameters.release>> --token $CIRCLE_TOKEN

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [# x]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - lint

      - orb-tools/pack:
          name: pack-validate
          workspace-path: orb.yml
          artifact-path: orb.yml
          requires:
            - lint

      - publish-dev:
          requires:
            - pack-validate
          context: orb-publishing

      - trigger-integration:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - publish-dev
          filters:
            branches:
              ignore: master

      - trigger-integration:
          name: trigger-integration-master
          context: orb-publishing
          tag: master
          requires:
            - publish-dev
          filters:
            branches:
              only: master

  integration_tests-prod_deploy:
    jobs:
      # triggered by non-master branch commits
      - test-orb-python:
          name: test-orb-python_dev
          filters: *integration-dev_filters

      - test-orb-azure-docker:
          name: test-orb-azure_dev
          filters: *integration-dev_filters

      - test-orb-golang:
          name: test-orb-golang_dev
          filters: *integration-dev_filters

      # triggered by master branch commits
      - test-orb-python:
          name: test-orb-python_master
          filters: *integration-master_filters

      - test-orb-azure-docker:
          name: test-orb-azure_master
          filters: *integration-master_filters

      - test-orb-golang:
          name: test-orb-golang_master
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - dev-promote-prod:
          name: dev-promote-minor
          release: minor
          context: orb-publishing
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - dev-promote-prod:
          name: dev-promote-major
          release: major
          context: orb-publishing
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
