---
description: >
  CircleCI official cimg/python Docker image to use

parameters:
  python-version:
    type: string
    default: "3.12.9"

docker:
  - image: cimg/python: <<parameters.python-version>>
